package com.scheduling.wise.domain.enums;

public enum AreaOfWork {
    ANESTHESIA,
    CARDIAC,
    COMMUNITY_HEALTH,
    CRITICAL_CARE,
    DIALYSIS,
    EMERGENCY,
    GERIATRIC,
    HOSPICE_AND_PALLIATIVE_CARE,
    HOME_HEALTH,
    INFECTIOUS_DISEASES,
    NEONATAL,
    OCCUPATIONAL_HEALTH,
    ONCOLOGY,
    PEDIATRIC,
    PSYCHIATRIC,
    PUBLIC_HEALTH,
    REHABILITATION,
    SCHOOL_NURSING,
    SURGICAL,
    TELEHEALTH;
}
